#!/bin/bash
# Description: Script to generate the tasks for ffs testing
# Author: Daniele Rondina, geaaru@funtoo.org

if [ -n "$DEBUG" ] ; then set -x ; fi

IMAGE_NAME="${IMAGE_NAME:-}"
ci_dir=$(dirname ${BASH_SOURCE[0]})/..
mottainai_values=${ci_dir}/mottainai.values

FIRE_TASK=${FIRE_TASK:-0}
TASKFILE=${TASKFILE:-/tmp/ffs-task.yaml}

main () {
  local isvalid=1

  if [ -z "${IMAGE_NAME}" ] ; then
    echo "Missing IMAGE_NAME env variable. Please select the image to test."
    return 1
  fi

  if [ -z "${MOTTAINAI_CLI_PROFILE}" ] ; then
    echo "Missing MOTTAINAI_CLI_PROFILE env variable."
    return 1
  fi

  isvalid=$(yq r ${mottainai_values} -j | jq ".values.images2test[] | select(.name==\"${IMAGE_NAME}\") | length")
  if [ "${isvalid}" == "0" ] ; then
    echo "Selected image not defined on mottainai.values file."
    return 1
  fi

  imagedata=$(yq r ${mottainai_values} -j | jq ".values.images2test[] | select(.name==\"${IMAGE_NAME}\")")

  image=$(echo "${imagedata}" | jq .image )
  prescripts=$(echo "${imagedata}" | jq '.pre_scripts // ""' | yq r - -P)
  envs=$(echo "${imagedata}" | jq '.environment // ""' | yq r - -P)
  arch=$(echo "${imagedata}" | jq '.arch // "x86_64bit"' | yq r - -P)

  mottainai-cli task compile ${ci_dir}/templates/test-ffs.yaml.tmpl \
    -s task_name="test ffs/${IMAGE_NAME}/${arch} - $(whoami)" \
    -s image="${image}" \
    -s "pre_scripts=${prescripts}" \
    -s "envs=${envs}" \
    -s "arch=${arch}" \
    -o ${TASKFILE} || return 1

  if [ "${FIRE_TASK}" = 1 ] ; then
    mottainai-cli task create --yaml ${TASKFILE}
  fi

  return 0
}

main $@
exit $?

# vim: filetype=sh
