sources:
  gnu:
    defaults:
      url: https://ftp.gnu.org/gnu/{name}/{name}-{version}.tar.{ext}
      ext: xz
    packages:
      - binutils: 2.38
      - mpfr: 4.1.0
      - gmp: 6.2.1
      - mpc:
          version: 1.2.1
          ext: gz
      - gcc:
          url: https://ftp.gnu.org/gnu/{name}/{name}-{version}/{name}-{version}.tar.{ext}
          version: 12.1.0
      - glibc: 2.35
      - ncurses:
          version: 6.3
          ext: gz
      - bash:
          version: 5.1.16
          ext: gz
      - bison: 3.8.2
      - coreutils: 9.1
      - diffutils: 3.8
      - findutils: 4.9.0
      - gawk: 5.1.1
      - gettext: 0.21
      - grep: 3.7
      - gzip: 1.12
      - make:
          version: 4.3
          ext: gz
      - m4:
          version: 1.4.19
      - patch: 2.7.6
      - sed: 4.8
      - tar: 1.34
      - texinfo:
          version: 6.8
          patches:
            - texinfo-6.8-glibc-2.34-compat.patch
      - nano: 6.2
  non-gnu:
    packages:
      - linux:
          version: 5.17.4
          url: https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-{version}.tar.xz
      - musl:
          version: 1.2.3
          url: https://musl.libc.org/releases/musl-{version}.tar.gz
      - isl:
          version: 0.24
          url: https://libisl.sourceforge.io/isl-{version}.tar.bz2
      - zlib:
          version: 1.2.12
          url: https://zlib.net/zlib-{version}.tar.gz
      - perl:
          version: 5.34.1
          url: https://www.cpan.org/src/5.0/perl-{version}.tar.gz
      - bzip2:
          version: 1.0.8
          url: https://www.sourceware.org/pub/bzip2/bzip2-{version}.tar.gz
      - check:
          version: 0.15.2
          url: https://github.com/libcheck/check/releases/download/{version}/check-{version}.tar.gz
      - file:
          version: 5.41
          url: http://ftp.astron.com/pub/file/file-{version}.tar.gz
      - rsync:
          version: 3.2.4
          url: https://download.samba.org/pub/rsync/src/rsync-{version}.tar.gz
      - util-linux:
          version: 2.38
          url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.38/util-linux-{version}.tar.gz
      - xz-utils:
          version: 5.2.5
          url: https://tukaani.org/xz/xz-{version}.tar.gz
          srcdir: xz-{version}
      - which:
          version: 2.21
          url: https://carlowood.github.io/which/which-{version}.tar.gz
      - python:
          version: 3.10.4
          url: https://www.python.org/ftp/python/{version}/Python-{version}.tar.xz
      - cmake:
          version: 3.23.1
          url: https://github.com/Kitware/CMake/releases/download/v{version}/cmake-{version}.tar.gz
      - libffi:
          version: 3.4.2
          url: https://github.com/libffi/libffi/releases/download/v{version}/libffi-{version}.tar.gz
      - openssl:
          version: 3.0.2
          url: https://www.openssl.org/source/openssl-{version}.tar.gz
