sources:
  gnu:
    defaults:
      url: https://ftp.gnu.org/gnu/{name}/{name}-{version}.tar.{ext}
      ext: xz
    packages:
      - autoconf: 2.69
      - automake: 1.15.1
      - libtool: 2.4.6
      - binutils: 2.38
      - mpfr: 4.1.0
      - gmp: 6.2.1
      - mpc:
          version: 1.2.1
          ext: gz
      - gcc:
          url: https://ftp.gnu.org/gnu/{name}/{name}-{version}/{name}-{version}.tar.{ext}
          version: 11.2.0
      - glibc: 2.33
      - ncurses:
          version: 6.3
          ext: gz
      - bash:
          version: 5.1.16
          ext: gz
      - bison: 3.4.1
      - coreutils: 9.1
      - diffutils: 3.7
      - findutils: 4.8.0
      - gawk: 5.1.0
      - gettext: 0.21
      - grep: 3.6
      - gzip: "1.10"
      - make:
          version: 4.2.1
          patches:
            - make-4.2.1-perl526.patch
            - make-4.2.1-glob-v2.patch
            - make-4.2.1-glob-internals.patch
            - make-4.2.1-pselect-non-blocking.patch
          ext: gz
      - m4:
          version: 1.4.19
      - patch: 2.7.6
      - sed: 4.8
      - tar: 1.34
      - texinfo: 6.7
      - nano: 6.3
      - wget:
          version: 1.21.3
          ext: gz
  non-gnu:
    packages:
      - linux:
          version: "5.10"
          url: https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-{version}.tar.xz
      - git:
          version: 2.36.1
          url: https://cdn.kernel.org/pub/software/scm/git/git-{version}.tar.xz
      - zlib:
          version: 1.2.13
          url: https://zlib.net/zlib-{version}.tar.gz
      - perl:
          version: 5.32.0
          url: https://www.cpan.org/src/5.0/perl-{version}.tar.gz
      - bzip2:
          version: 1.0.8
          url: https://www.sourceware.org/pub/bzip2/bzip2-{version}.tar.gz
      - check:
          version: 0.12.0
          url: https://github.com/libcheck/check/releases/download/{version}/check-{version}.tar.gz
      - file:
          version: 5.42
          url: http://ftp.astron.com/pub/file/file-{version}.tar.gz
      - rsync:
          version: 3.2.4
          url: https://download.samba.org/pub/rsync/src/rsync-{version}.tar.gz
      - util-linux:
          version: 2.38
          url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.38/util-linux-{version}.tar.gz
      - xz-utils:
          version: 5.2.5
          url: https://tukaani.org/xz/xz-{version}.tar.gz
          srcdir: xz-{version}
      - zstd:
          version: 1.5.2
          url: https://github.com/facebook/zstd/releases/download/v{version}/zstd-{version}.tar.gz
      - which:
          version: 2.21
          url: https://carlowood.github.io/which/which-{version}.tar.gz
      - pkgconf:
          version: 1.5.4
          url: https://distfiles.ariadne.space/pkgconf/pkgconf-{version}.tar.xz
      - python:
          version: 3.9.13
          url: https://www.python.org/ftp/python/{version}/Python-{version}.tar.xz
          srcdir: Python-{version}
      - cmake:
          version: 3.19.7
          url: https://github.com/Kitware/CMake/releases/download/v{version}/cmake-{version}.tar.gz
      - libffi:
          version: 3.3-rc0
          url: https://github.com/libffi/libffi/releases/download/v{version}/libffi-{version}.tar.gz
      - curl:
          version: 7.83.1
          url: https://github.com/curl/curl/releases/download/curl-7_83_1/curl-{version}.tar.bz2
      - openssl:
          version: 1.1.1n
          url: https://www.openssl.org/source/openssl-{version}.tar.gz
      - pax-utils:
          version: 1.2.4
          url: https://gitweb.gentoo.org/proj/pax-utils.git/snapshot/pax-utils-{version}.tar.bz2
      - sandbox:
          version: 2.24
          url: https://gitweb.gentoo.org/proj/sandbox.git/snapshot/sandbox-{version}.tar.bz2
      - portage:
          version: 3.0.14-r10
          srcdir: zmedico-portage-261f0f7
          url: https://github.com/zmedico/portage/tarball/261f0f763888d9392927a6cae2af50292fc694a1 -> portage-3.0.14-r10.tar.gz
          patches:
            - portage-2.4.3-remove-gentoo-repos-conf.patch
            - portage-2.3.68-change-global-paths.patch
            - portage-2.3.41-ebuild-nodie.patch
            - portage-2.3.68-set-backtracking-to-6.patch
            - portage-3.0.9-enhanced-metadata.patch
            - portage-2.3.78-static-libs-belong-where-I-put-them.patch
            - portage-2.3.78-module-rebuild.patch
            - portage-3.0.9-add-repodir-variable.patch
            - portage-3.0.14-allow-matches-in-package-updates.patch
            - portage-3.0.14-track-and-deny-keywords-r1.patch
            - portage-3.0.14-aliases-name-check.patch
            - portage-3.0.14-cdn-feature-ignore-mirror.patch
      - ego:
          version: 2.8.6
          url: https://github.com/funtoo/ego/archive/refs/tags/{version}.tar.gz
