# Targets for generate Mottainai tasks/pipeline

.PHONY: all
all:
	@echo "gen-test-task                   Generate and fire the task for testing ffs on"
	@echo "                                selected image."

.PHONY: gen-test-task
gen-test-task:
	@make/test-tasks
