#!/bin/bash
export TEST_NAME="cinnamon"
export EGO_PROFILE_FLAVOR=desktop
export EGO_PROFILE_MIX_INS="gnome gfxcard-nouveau gfxcard-intel"
export EMERGE_PACKAGES="gnome-extra/cinnamon"
../bin/image-create ${TEST_NAME}-test
