#!/bin/bash
export TEST_NAME="${0##*/}"
export TEST_MODE="runtest"
export TEST_RUN_EXEC=/var/tmp/gnome-upgrade-test
export EGO_PROFILE_FLAVOR=desktop
export EGO_PROFILE_MIX_INS="gnome gfxcard-nouveau"
../bin/image-create
